# Generated by Django 5.1.6 on 2025-03-30 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridgeitem',
            options={'ordering': ['expiry_date', 'ingredient__name'], 'verbose_name': 'Produkt w lodówce', 'verbose_name_plural': 'Produkty w lodówce'},
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania'),
        ),
    ]
