# Generated by Django 5.1.6 on 2025-03-28 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
        ('recipes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridgeitem',
            options={'verbose_name': 'Produkt w lodówce', 'verbose_name_plural': 'Produkty w lodówce'},
        ),
        migrations.AlterUniqueTogether(
            name='fridgeitem',
            unique_together={('user', 'ingredient', 'unit', 'expiry_date')},
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Ilość'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Składnik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data zakupu'),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data ważności'),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.measurementunit', verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_items', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.RemoveField(
            model_name='fridgeitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fridgeitem',
            name='quantity',
        ),
    ]
