# Generated by Django 5.1.7 on 2025-03-29 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge_name', models.CharField(default='Moja Lodówka', max_length=100, verbose_name='Nazwa lodówki')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Zdjęcie profilowe')),
                ('bio', models.TextField(blank=True, verbose_name='O sobie')),
                ('favorite_cuisine', models.CharField(blank=True, max_length=100, verbose_name='Ulubiona kuchnia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil użytkownika',
                'verbose_name_plural': 'Profile użytkowników',
            },
        ),
    ]
