# Generated by Django 5.2 on 2025-04-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recipehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fridge_name',
        ),
    ]
