# Generated by Django 5.1.7 on 2025-03-29 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('is_vegetarian', models.BooleanField(default=True, verbose_name='Wegetariański')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Wegański')),
            ],
            options={
                'verbose_name': 'Kategoria składnika',
                'verbose_name_plural': 'Kategorie składników',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa jednostki')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('is_base', models.BooleanField(default=False, verbose_name='Jednostka bazowa')),
            ],
            options={
                'verbose_name': 'Jednostka miary',
                'verbose_name_plural': 'Jednostki miary',
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Kategoria przepisu',
                'verbose_name_plural': 'Kategorie przepisów',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa składnika')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.ingredientcategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Składnik',
                'verbose_name_plural': 'Składniki',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('instructions', models.TextField(verbose_name='Instrukcje przygotowania')),
                ('servings', models.PositiveIntegerField(default=4, verbose_name='Liczba porcji')),
                ('preparation_time', models.PositiveIntegerField(help_text='Czas przygotowania w minutach', verbose_name='Czas przygotowania')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categories', models.ManyToManyField(related_name='recipes', to='recipes.recipecategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Przepis',
                'verbose_name_plural': 'Przepisy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Ilość')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Składnik')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='Przepis')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.measurementunit', verbose_name='Jednostka')),
            ],
            options={
                'verbose_name': 'Składnik przepisu',
                'verbose_name_plural': 'Składniki przepisu',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField(verbose_name='Współczynnik konwersji')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='recipes.measurementunit', verbose_name='Z jednostki')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='recipes.measurementunit', verbose_name='Na jednostkę')),
            ],
            options={
                'verbose_name': 'Konwersja jednostek',
                'verbose_name_plural': 'Konwersje jednostek',
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
