# Generated by Django 5.1.6 on 2025-03-30 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', 'setup_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('user', 'date', 'meal_type', 'recipe')},
        ),
    ]
