# Generated by Django 5.1.6 on 2025-03-30 22:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementunit',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Opis/przykład'),
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Popularna miara kuchenna'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='base_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Przelicznik bazowy (w gramach lub mililitrach)'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='type',
            field=models.CharField(choices=[('weight', 'Waga'), ('volume', 'Objętość'), ('piece', 'Sztuki'), ('spoon', 'Łyżki'), ('custom', 'Inne')], default='weight', max_length=20, verbose_name='Typ jednostki'),
        ),
        migrations.CreateModel(
            name='IngredientUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='Domyślna jednostka')),
                ('conversion_info', models.CharField(blank=True, max_length=100, verbose_name='Informacja o przeliczniku')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_units', to='recipes.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.measurementunit')),
            ],
            options={
                'verbose_name': 'Jednostka składnika',
                'verbose_name_plural': 'Jednostki składników',
                'unique_together': {('ingredient', 'unit')},
            },
        ),
    ]
