# Generated by Django 5.1.6 on 2025-03-29 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='barcode',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Kod kreskowy'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_ingredients', to='recipes.measurementunit', verbose_name='Domyślna jednostka'),
        ),
    ]
