# Generated by Django 5.1.6 on 2025-03-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_barcode_ingredient_default_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='compatible_units',
            field=models.ManyToManyField(blank=True, related_name='compatible_ingredients', to='recipes.measurementunit', verbose_name='Kompatybilne jednostki'),
        ),
    ]
