# Generated by Django 5.1.6 on 2025-03-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_measurementunit_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
