# Generated by Django 5.1.6 on 2025-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_meal_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_type',
            field=models.CharField(choices=[('weight_only', 'Tylko waga (g, kg)'), ('volume_only', 'Tylko objętość (ml, l)'), ('piece_only', 'Tylko sztuki'), ('weight_volume', 'Waga i objętość'), ('weight_piece', 'Waga i sztuki'), ('weight_spoon', 'Waga i łyżki'), ('volume_spoon', 'Objętość i łyżki'), ('all', 'Wszystkie jednostki')], default='weight_only', max_length=20, verbose_name='Dozwolone jednostki'),
        ),
    ]
