# Generated by Django 5.1.6 on 2025-03-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='category',
            field=models.CharField(choices=[('meat', 'Mięsny'), ('animal', 'Pochodzenia zwierzęcego'), ('plant', 'Roślinny')], default='plant', max_length=10),
        ),
    ]
