# Generated by Django 5.2 on 2025-04-10 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredientconversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa tablicy')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('product_type', models.CharField(max_length=50, verbose_name='Typ produktu')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Zatwierdzona')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversion_tables', to=settings.AUTH_USER_MODEL, verbose_name='Utworzona przez')),
            ],
            options={
                'verbose_name': 'Tablica konwersji',
                'verbose_name_plural': 'Tablice konwersji',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa składnika')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('density', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Gęstość [g/ml]')),
                ('piece_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Waga sztuki [g]')),
                ('unit_type', models.CharField(choices=[('weight_only', 'Tylko waga (g, kg)'), ('volume_only', 'Tylko objętość (ml, l)'), ('piece_only', 'Tylko sztuki'), ('weight_volume', 'Waga i objętość'), ('weight_piece', 'Waga i sztuki'), ('weight_spoon', 'Waga i łyżki'), ('volume_spoon', 'Objętość i łyżki'), ('all', 'Wszystkie jednostki')], default='weight_only', max_length=20, verbose_name='Dozwolone jednostki')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zgłoszenia')),
                ('status', models.CharField(choices=[('pending', 'Oczekujący'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Uwagi administratora')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.ingredientcategory', verbose_name='Kategoria')),
                ('conversion_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ingredients', to='recipes.conversiontable', verbose_name='Tablica konwersji')),
                ('default_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.measurementunit', verbose_name='Domyślna jednostka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_ingredients', to=settings.AUTH_USER_MODEL, verbose_name='Zgłoszone przez')),
            ],
            options={
                'verbose_name': 'Składnik użytkownika',
                'verbose_name_plural': 'Składniki użytkowników',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Współczynnik konwersji')),
                ('is_exact', models.BooleanField(default=True, verbose_name='Dokładna konwersja')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.measurementunit', verbose_name='Z jednostki')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='recipes.conversiontable', verbose_name='Tablica konwersji')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.measurementunit', verbose_name='Na jednostkę')),
            ],
            options={
                'verbose_name': 'Wpis tablicy konwersji',
                'verbose_name_plural': 'Wpisy tablicy konwersji',
                'ordering': ['table', 'from_unit__name', 'to_unit__name'],
                'unique_together': {('table', 'from_unit', 'to_unit')},
            },
        ),
    ]
