# Generated by Django 5.2 on 2025-04-14 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_conversiontable_useringredient_conversiontableentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversiontable',
            options={'ordering': ['category__name', 'name'], 'verbose_name': 'Tablica konwersji', 'verbose_name_plural': 'Tablice konwersji'},
        ),
        migrations.RemoveField(
            model_name='conversiontable',
            name='product_type',
        ),
        migrations.AddField(
            model_name='conversiontable',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversion_tables', to='recipes.ingredientcategory', verbose_name='Kategoria produktów'),
        ),
        migrations.AddField(
            model_name='conversiontable',
            name='is_for_liquids',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeśli ta tablica jest przeznaczona dla produktów płynnych', verbose_name='Dla płynów'),
        ),
    ]
