# Generated by Django 5.2 on 2025-04-15 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_ratinghelpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperating',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='recipes.reciperating', verbose_name='Odpowiedź na ocenę'),
        ),
    ]
