# Generated by Django 5.1.6 on 2025-03-30 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa listy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Zakończona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Lista zakupów',
                'verbose_name_plural': 'Listy zakupów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Ilość')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Zakupione')),
                ('purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='Data zakupu')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Notatka')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Składnik')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe', verbose_name='Przepis')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.measurementunit', verbose_name='Jednostka')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist', verbose_name='Lista zakupów')),
            ],
            options={
                'verbose_name': 'Pozycja na liście zakupów',
                'verbose_name_plural': 'Pozycje na liście zakupów',
                'ordering': ['ingredient__name'],
            },
        ),
    ]
